using Microsoft.Maui.Devices;
namespace MauiSensors.Views.Graphics
{
    public class AccelerometerGraphics : IDrawable
    {
        public AccelerometerGraphics()
        {
        }

        private double _xAccell;
        private double _yAccell;
        private double _zAccell;

        public void SetAccelerometerReading(double x, double y, double z)
        {
            // Set the accelerometer readings
            _xAccell = x;
            _yAccell = y;
            _zAccell = z;
        }

        /// <summary>
        /// Draw the accelerometer graphics
        /// </summary>
        /// <param name="canvas"></param>
        /// <param name="dirtyRect"></param>
        public void Draw(ICanvas canvas, RectF dirtyRect)
        {
            var orientation = DeviceDisplay.MainDisplayInfo.Orientation;
            // The code below was entirely generated by Copilot

            //Calculate the tilt angle (pitch or roll) based on the accelerometer readings.
            var pitch = Math.Atan2(_xAccell, Math.Sqrt(_yAccell * _yAccell + _zAccell * _zAccell));
            var roll = Math.Atan2(_yAccell, Math.Sqrt(_xAccell * _xAccell + _zAccell * _zAccell));

            // Draw the tilt angle on the screen

            //canvas.FillColor = Colors.Black;
            //canvas.FillRectangle(0, 0, dirtyRect.Width, dirtyRect.Height);
            //canvas.StrokeColor = Colors.White;
            //canvas.StrokeSize = 2;
            //canvas.DrawLine(0, dirtyRect.Height / 2, dirtyRect.Width, dirtyRect.Height / 2);
            //canvas.DrawLine(dirtyRect.Width / 2, 0, dirtyRect.Width / 2, dirtyRect.Height);
            //canvas.StrokeSize = 4;
            //canvas.StrokeColor = Colors.Red;
            //canvas.DrawLine(dirtyRect.Width / 2, dirtyRect.Height / 2, dirtyRect.Width / 2 + (float)(Math.Cos(pitch) * 100), dirtyRect.Height / 2 + (float)(Math.Sin(pitch) * 100));
            //canvas.StrokeColor = Colors.Green;
            //canvas.DrawLine(dirtyRect.Width / 2, dirtyRect.Height / 2, dirtyRect.Width / 2 + (float)(Math.Cos(roll) * 100), dirtyRect.Height / 2 + (float)(Math.Sin(roll) * 100));

            //canvas.FillColor = Colors.White;
            //if (orientation == DisplayOrientation.Landscape)
            //{
            //    canvas.FillCircle(dirtyRect.Width / 2 + (float)(Math.Cos(roll) * 100), dirtyRect.Height / 2 + (float)(Math.Sin(roll) * 100), 10);
            //}
            //else
            //{
            //    canvas.FillCircle(dirtyRect.Width / 2 + (float)(Math.Cos(pitch) * 100), dirtyRect.Height / 2 + (float)(Math.Sin(pitch) * 100), 10);
            //}



            // The code below is Pierre's implementation of the above code using two different skeuomorphic designs 
            // 1 - Use a plumb when in landscape mode
            // 2 - Use a spirit level bubble when in portrait mode

            if (orientation == DisplayOrientation.Landscape)
            {
                // Draw the plumb Bob
                canvas.FillColor = Colors.Black;
                canvas.FillRectangle(0, 0, dirtyRect.Width, dirtyRect.Height);
                canvas.StrokeColor = Colors.White;
                canvas.StrokeSize = 2;
                canvas.DrawLine(0, dirtyRect.Height / 2, dirtyRect.Width, dirtyRect.Height / 2);
                canvas.DrawLine(dirtyRect.Width / 2, 0, dirtyRect.Width / 2, dirtyRect.Height);
                canvas.StrokeSize = 4;
                canvas.StrokeColor = Colors.Red;
                canvas.DrawLine(dirtyRect.Width / 2, dirtyRect.Height / 2, dirtyRect.Width / 2 + (float)(Math.Cos(pitch) * 100), dirtyRect.Height / 2 + (float)(Math.Sin(pitch) * 100));
                canvas.StrokeColor = Colors.Green;

                canvas.FillCircle(dirtyRect.Width / 2 + (float)(Math.Cos(roll) * 100), dirtyRect.Height / 2 + (float)(Math.Sin(roll) * 100), 10);
            }
            else
            {
                // Draw the spirit level bubble
                canvas.FillColor = Colors.White;
                canvas.FillCircle(dirtyRect.Width / 2 + (float)(Math.Cos(pitch) * 100), dirtyRect.Height / 2 + (float)(Math.Sin(pitch) * 100), 10);
            }

        }
    }
}
